import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link'

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Tsz Him Lai | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={"scroll-smooth"}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased text-pink-100`}
        >
        <div
            className="z-50 flex sticky top-0 h-12 flex-row text-pink-300 items-center border-b-2 backdrop-brightness-0">
            <Link href="/" className="p-10 text-2xl font-bold">Tsz Him Lai</Link>
            <Link href="/#Projects" className={"ease-in-out"}>Projects</Link>
        </div>
        {children}
        <div className="h-[200px]"/>
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center pb-5 pt-4">
            <Link
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="/#Projects"
                rel="noopener noreferrer"
            >
                Projects
            </Link>
        </footer>
        </body>
        </html>
    );
}
